<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a9ae8cff-e1ef-49c7-99e4-c352c2a07a81</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingApp.Application\ShoppingApp.Application.csproj" />
    <ProjectReference Include="..\ShoppingApp.Infrastructure\ShoppingApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
